//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptekaIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImages
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public byte[] ImageData { get; set; }
        public string ContentType { get; set; }
        public bool IsMain { get; set; }
        public System.DateTime UploadedAt { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
