//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptekaIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductImages = new HashSet<ProductImages>();
            this.ReceiptItems = new HashSet<ReceiptItems>();
            this.RequestItems = new HashSet<RequestItems>();
            this.SaleItems = new HashSet<SaleItems>();
            this.SpecialProperties = new HashSet<SpecialProperties>();
            this.WriteOffs = new HashSet<WriteOffs>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> PackageTypeId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string Dosage { get; set; }
        public string Volume { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool PrescriptionRequired { get; set; }
        public string Description { get; set; }
        public string Substance { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual PackageTypes PackageTypes { get; set; }
        public virtual ProductForms ProductForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImages> ProductImages { get; set; }
        public virtual SubCategories SubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptItems> ReceiptItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestItems> RequestItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItems> SaleItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialProperties> SpecialProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WriteOffs> WriteOffs { get; set; }
    }
}
