//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptekaIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipts()
        {
            this.ReceiptItems = new HashSet<ReceiptItems>();
        }
    
        public int Id { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int RequestId { get; set; }
        public int SupplierId { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptItems> ReceiptItems { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Requests Requests { get; set; }
    }
}
